name: Deploy Evergreen App

on:
  push:
    branches:
      - main  # Change to 'master' if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t techiemithlesh/evegreen-app:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push techiemithlesh/evegreen-app:latest

      - name: Deploy to Server
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Checking for existing container..."
            if docker ps -a --format '{{.Names}}' | grep -q 'evegreen-app'; then
              echo "Stopping and removing old container..."
              docker stop evegreen-app
              docker rm evegreen-app
            else
              echo "No existing container found."
            fi

            echo "Cleaning up unused images and volumes..."
            docker system prune -af --volumes

            echo "Pulling latest Docker image..."
            docker pull techiemithlesh/evegreen-app:latest

            echo "Starting new container on port 80..."
            docker run -d --name evegreen-app --restart=always -p 80:80 techiemithlesh/evegreen-app:latest

            echo "Deployment complete! Your app is live at http://18.119.161.134"
