name: Deploy Evergreen App

on:
  push:
    branches:
      - main  # Triggers deployment when code is pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build --no-cache -t techiemithlesh/evergreen-app:latest .
          docker push techiemithlesh/evergreen-app:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        if: success()
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🚀 Starting Deployment on Server..."

            # Move to project directory
            cd ~/evegreen || { echo "❌ Directory not found!"; exit 1; }

            echo "🛑 Stopping existing containers..."
            docker-compose down

            echo "🧹 Cleaning up old Docker images..."
            docker system prune -af --volumes

            echo "📥 Pulling the latest image..."
            docker pull techiemithlesh/evergreen-app:latest

            echo "🔄 Restarting services..."
            docker-compose up -d --build

            echo "🛠 Running Laravel Optimizations..."
            docker-compose exec -T app php artisan cache:clear
            docker-compose exec -T app php artisan config:clear
            docker-compose exec -T app php artisan route:clear
            docker-compose exec -T app php artisan view:clear
            docker-compose exec -T app php artisan optimize

            echo "🎉 Deployment Successful! App is live at http://${{ secrets.SERVER_HOST }}"
