- name: Deploy to Server
  if: success()
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.SERVER_HOST }}
    username: ${{ secrets.SERVER_USER }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    script: |
      echo "Switching to project directory..."
      cd ~/evegreen || { echo "Directory not found!"; exit 1; }

      echo "Checking for docker-compose.yml..."
      ls -l docker-compose.yml || { echo "docker-compose.yml missing!"; exit 1; }

      echo "Stopping existing containers..."
      docker-compose down

      echo "Cleaning up unused images and volumes..."
      docker system prune -af --volumes

      echo "Pulling latest image..."
      docker pull techiemithlesh/evergreen-app:latest

      echo "Starting Docker Compose..."
      docker-compose up -d --build

      echo "Deployment complete! Your app is live at http://${{ secrets.SERVER_HOST }}"
