name: Deploy Evergreen App

on:
  push:
    branches:
      - main  # Change to 'master' if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t techiemithlesh/evegreen-app:latest .
      
      - name: Push Docker image to Docker Hub
        run: |
          docker push techiemithlesh/evegreen-app:latest

      - name: Deploy to Server (Optional)
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull techiemithlesh/evegreen-app:latest
            docker stop evegreen-app || true
            docker rm evegreen-app || true
            docker run -d --name evegreen-app -p 80:80 techiemithlesh/evegreen-app:latest

